# The required mandatory fields are name: and environment - sdk only. They are enough to develop a dart package.

# Press ctrl + space to see the list of available properties.

# all lowercase with underscores only
# This will be a package too, so it can't be same with existing package!


name: dart_basic
description: A sample command-line application.
version: 1.0.0

homepage: https://www.example.com
repository: https://github.com/project_name
issue_tracker: 
documentation: https://document.com

# Set this to none if you don't want to publish to pub.dev
publish_to: none

executables: 
  dart_basic: main # If this package is activated by `dart pub global active dart_basic`, `dart_basic` will execute bin/main.dart
  basic:           # `basic` will execute bin/dart_basic.dart


# https://dart.dev/tools/pub/pubspec#sdk-constraints
# As of Dart 1.19.0, pub supports Flutter SDK constraints under the environment: field:
# We need to specify flutter sdk version here as it doesn't seem to be easily possible to figure out flutter sdk version from dart sdk version
# environment:
#   sdk: '>=1.19.0 <3.0.0'
#   flutter: ^0.1.2
environment:
  # use traditional syntax here
  sdk: '>=2.14.2 <3.0.0' # Dart version for this package

# Use caret syntax in deepencies
# dependencies:
#   path: ^1.8.0

# Use caret syntax in deepencies
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
